use_frameworks!

target 'TUSKit_Example' do
  pod 'TUSKit', :path => '../'

  target 'TUSKit_Tests' do
    inherit! :search_paths
    pod 'AppSpectorSDK'
    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 6.3.0'
  end
end
